name: Capital Solutions
favicon: null
layout_spectrum: 0.42414
typography_spectrum: 0.43099870765581727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#282723'
    - '#0c0808'
    - '#554f45'
    - '#b2a69a'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.2937533538788557
  rhythmicContrast: 0.25
purpose: []
